const DEFAULT_PAGINATION_SKIP = 0;
const DEFAULT_PAGINATION_TAKE = 12;

const DEFAULT_URL = 'http://localhost:4000';


export default {
  DEFAULT_URL,
  DEFAULT_PAGINATION_SKIP,
  DEFAULT_PAGINATION_TAKE,
};
